### ISSUE TITLE
Linux: Error starting node

### ISSUE THREAD

**Issue by devaux** [nano-wallet-company/nano-wallet-desktop#58]
$ nano-wallet-desktop 

(nano-wallet-desktop:25181): Gtk-WARNING **: 08:29:17.884: Theme parsing error: gtk-main.css:73:38: Failed to import: Fehler beim Öffnen der Datei »/usr/share/themes/Radiance/gtk-3.20/apps/gnome-builder.css«: Datei oder Verzeichnis nicht gefunden
[08:29:18.931] [info] Starting application: Nano Wallet Desktop 1.0.0 (production)
[08:29:19.205] [info] Electron's autoUpdater does not support the 'linux' platform
[08:29:20.068] [info] Application window ready to show: Nano Wallet Desktop
[08:29:20.898] [info] Writing node configuration version 2: /home/user/.config/Nano Wallet Desktop/config.json
[08:29:21.165] [info] Starting node: /usr/lib/nano-wallet-desktop/resources/app.asar.unpacked/ember-electron/resources/rai_node
[08:29:21.177] [info] Node started (PID 25264, RPC port 35019, peering port 40121)
[08:29:21.240] [info] Generating TLS certificate: rpc.nanowalletcompany.com
[08:29:24.195] [info] Waiting for node to be ready on ::1:35019...
[08:29:24.198] [error] Error starting node: Error: connect EADDRNOTAVAIL ::1:35019 - Local (:::0)
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at internalConnect (net.js:971:16)
    at net.js:1065:9
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

[08:30:01.948] [error] [node] Error while running node (Cannot assign requested address)
[08:30:01.951] [info] Node exiting (PID 25264)
[08:30:01.952] [info] Proxy server closing

**Comment by devaux** [comment]
No it never worked. On all my Linux hosts (Ubuntu/Arch) i get the same error.
As i can remember, i had similar issue with the 14-version. But a few minutes after starting the programm it started to sync...

**Comment by kennedybaird** [comment]
Are these Linux hosts virtual machines inside Windows?

Can you give more details on your environment.

It may be an IPv6/v4 error

**Comment by devaux** [comment]
I was thinking the same, so i disabled IPv6 completely in networkmanager. But without success.
Both are physical hosts - but without IPv6-dhcp-announcements. After enabling IPv6 my network looks this way:

$ ifconfig 
eno1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.96.108  netmask 255.255.252.0  broadcast 192.168.99.255
        inet6 fe80::af81:51e2:1bcd:35bc  prefixlen 64  scopeid 0x20<link>
        ether fc:4d:d4:d3:34:f1  txqueuelen 1000  (Ethernet)
        RX packets 83490851  bytes 53376852303 (53.3 GB)
        RX errors 0  dropped 463  overruns 0  frame 0
        TX packets 43533926  bytes 6397782712 (6.3 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 20  memory 0xf7c00000-f7c20000  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Lokale Schleife)
        RX packets 44290381  bytes 30616865810 (30.6 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 44290381  bytes 30616865810 (30.6 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by kennedybaird** [comment]
The node is dependent on IPv6.

https://github.com/nanocurrency/raiblocks/issues/399

```
Right now rai_lib uses IPv4-mapped region of IPv6. Hosts w/o a dual-stack will see failures to bind to addresses (EADDRNOTAVAIL etc)
```

**Comment by devaux** [comment]
Is there a workaround to use the desktop-wallet on a pc without IPv6?

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
