### ISSUE TITLE
The wallet should fallback to regular bootstrapping if the download of data.tar.xz fails

### ISSUE THREAD

**Issue by alexbakker** [nano-wallet-company/nano-wallet-desktop#87]
I get the following error when trying to start the wallet:

```
$ ./nano-wallet-desktop
[15:09:21.444] [info] Starting application: Nano Wallet Desktop 1.1.0 (production)
[15:09:21.519] [info] Electron's autoUpdater does not support the 'linux' platform
[15:09:22.097] [info] Application window ready to show: Nano Wallet Desktop
[15:09:22.886] [info] Downloading asset: https://dkl5m4kebds7n.cloudfront.net/data.tar.xz
[15:09:24.224] [error] Error downloading asset: Error: The download of data.tar.xz was interrupted
    at DownloadItem.item.on (/home/alex/Downloads/nano-wallet-desktop-linux-x64/resources/app.asar/node_modules/electron-dl/index.js:109:8)
    at emitTwo (events.js:131:20)
    at DownloadItem.emit (events.js:214:7)
```

Instead of getting stuck on the load screen, it should fallback to bootstrapping off the other nodes in the network.

**Comment by alexbakker** [comment]
My bad, I somehow managed to start the old 1.1.0 version I head laying around instead of 1.5.0. I don't get the error anymore, but still think the fallback would be a good idea.

**Comment by zhyatt** [comment]
The NanoWalletCompany is no longer supporting this app. See https://nanowalletcompany.com/ for details. Closing.
